module.exports = {
  menu: require('../../assets/icons/menu.png'),
  home: require('../../assets/icons/home.png'),
  back: require('../../assets/icons/back.png'),
  li: require('../../assets/icons/arrow-right-icon.png'),
  
  activation_icon: require('../../assets/icons/activation-icon.png'),
  
  scoreboard: require('../../assets/icons/scoreboard.png'),
  forms: require('../../assets/icons/forms.png'),
  contact: require('../../assets/icons/contact.png'),
  orders: require('../../assets/icons/target.png'),
  promo: require('../../assets/icons/promo.png'),
  news: require('../../assets/icons/email.png'),
  profile: require('../../assets/icons/profile.png'),
  // mtdSales: require('../../assets/icons/stock-purchase-icon.png'),
  incentives: require('../../assets/icons/incentive-icon.png'),
  logout: require('../../assets/icons/logout.png'),
  
  
  placeholder: require('../../assets/icons/placeholder.jpeg'),
  pinksquare: require('../../assets/icons/pinksq.png'),
  greensquare: require('../../assets/icons/greensq.png'),
  purplesquare: require('../../assets/icons/purplesq.png'),
  orangesquare: require('../../assets/icons/orangesq.png'),
  deepgreensquare: require('../../assets/icons/deepgreensq.png'),
  redsquare: require('../../assets/icons/redsq.png'),
  yellowsquare: require('../../assets/icons/yellowsq.png'),
  revbluesquare: require('../../assets/icons/revbluesq.png'),
  closeicon: require('../../assets/icons/close.png'),
  check: require('../../assets/icons/check.png'),
  ellipse: require('../../assets/icons/Ellipse.png'),
  ellipse11: require('../../assets/icons/Ellipse11.png'),
  headerlogo: require('../../assets/img/headerlogo.png'),
  closeform: require('../../assets/icons/closeform.png'),
};
