module.exports = {
  menu: require('../../assets/icons/menu.png'),
  home: require('../../assets/icons/home.png'),
  scoreboard: require('../../assets/icons/scoreboard.png'),
  shop: require('../../assets/icons/shop.png'),
  orders: require('../../assets/icons/shoppingList.png'),
  promo: require('../../assets/icons/shoppingCart.png'),
  news: require('../../assets/icons/email.png'),
  profile: require('../../assets/icons/profile.png'),
  mtdSales: require('../../assets/icons/stock-purchase-icon.png'),
  incentives: require('../../assets/icons/incentive-icon.png'),
  logout: require('../../assets/icons/logout.png'),
  cartB: require('../../assets/icons/cartB.png'),
  cartO: require('../../assets/icons/cartO.png'),
  placeholder: require('../../assets/icons/placeholder.jpg'),
};
